#!/bin/bash

exe=$(which clang-format)

if [ -n "$exe" ]
then

  IFS=$'\n'

  for line in $(git status -s)
  do
    # If the file is added or modified
    if [[ $line == A* || $line == M* ]]
    then
      # And the file is .h or .cpp
      if [[$line == *.h || $line == *.cpp ]]
      then
        # Format the file
        clang-format-6.0 -i -style=file $(pwd)/${line:3}

        # And then add the file (so that any formatting changes get committed)
        git add $(pwd)/${line:3}
      fi
    fi
  done
else
  echo "Not found files for format."
fi
